# Cross-build Windows binaries with clang-cl and the Microsoft CRT/SDK.
# xwin 0.10.0 provides the SDK layout used here. No SDK files are redistributed.
# cmake -S . -B build_cross_x64 -G Ninja \
#   -DCMAKE_TOOLCHAIN_FILE=cmake/ClangWindows.cmake \
#   -DJEV_WINDOWS_SDK_ROOT=/path/to/xwin/splat -DJEV_WINDOWS_ARCH=x86_64
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_VERSION 10.0)
set(CMAKE_TRY_COMPILE_CONFIGURATION Release)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
set(JEV_WINDOWS_ARCH "x86_64" CACHE STRING "Windows target: x86_64 or x86")
set(JEV_WINDOWS_SDK_ROOT "" CACHE PATH "xwin splat output directory")
if(NOT JEV_WINDOWS_ARCH MATCHES "^(x86_64|x86)$")
    message(FATAL_ERROR "JEV_WINDOWS_ARCH must be x86_64 or x86")
endif()
if(NOT EXISTS "${JEV_WINDOWS_SDK_ROOT}/crt/include")
    message(FATAL_ERROR "Set JEV_WINDOWS_SDK_ROOT to an xwin splat directory")
endif()
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES JEV_WINDOWS_ARCH JEV_WINDOWS_SDK_ROOT)
set(CMAKE_SYSTEM_PROCESSOR ${JEV_WINDOWS_ARCH})
find_program(CMAKE_C_COMPILER NAMES clang-cl-19 clang-cl REQUIRED)
set(CMAKE_CXX_COMPILER ${CMAKE_C_COMPILER})
find_program(CMAKE_LINKER NAMES lld-link-19 lld-link REQUIRED)
find_program(CMAKE_RC_COMPILER NAMES llvm-rc-19 llvm-rc REQUIRED)
find_program(CMAKE_MT NAMES llvm-mt-19 llvm-mt)
if(JEV_WINDOWS_ARCH STREQUAL "x86")
    set(_jev_target i686-pc-windows-msvc)
else()
    set(_jev_target x86_64-pc-windows-msvc)
endif()
set(CMAKE_C_COMPILER_TARGET ${_jev_target})
set(CMAKE_CXX_COMPILER_TARGET ${_jev_target})
set(_jev_includes "")
set(_jev_rc_includes "")
foreach(_jev_include crt/include sdk/include/ucrt sdk/include/shared
        sdk/include/um sdk/include/winrt sdk/include/cppwinrt)
    string(APPEND _jev_includes " -imsvc \"${JEV_WINDOWS_SDK_ROOT}/${_jev_include}\"")
    string(APPEND _jev_rc_includes " -I\"${JEV_WINDOWS_SDK_ROOT}/${_jev_include}\"")
endforeach()
set(CMAKE_C_FLAGS_INIT "${_jev_includes}")
set(CMAKE_CXX_FLAGS_INIT "${_jev_includes}")
set(CMAKE_RC_FLAGS_INIT "-c 65001 ${_jev_rc_includes}")
set(_jev_libpaths "")
foreach(_jev_lib crt/lib/${JEV_WINDOWS_ARCH} sdk/lib/ucrt/${JEV_WINDOWS_ARCH}
        sdk/lib/um/${JEV_WINDOWS_ARCH})
    string(APPEND _jev_libpaths " /libpath:\"${JEV_WINDOWS_SDK_ROOT}/${_jev_lib}\"")
endforeach()
set(CMAKE_EXE_LINKER_FLAGS_INIT "${_jev_libpaths}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_jev_libpaths}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_jev_libpaths}")
set(CMAKE_FIND_ROOT_PATH ${JEV_WINDOWS_SDK_ROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
