file(READ "${CMAKE_SOURCE_DIR}/data/jev-product.json" JEV_PRODUCT_JSON)
string(JSON JEV_VERSION GET "${JEV_PRODUCT_JSON}" version)
if(NOT JEV_VERSION STREQUAL PROJECT_VERSION)
    message(FATAL_ERROR "jev-product.json version must match project VERSION")
endif()

function(jev_guid_initializer key output)
    string(JSON guid GET "${JEV_PRODUCT_JSON}" "${key}")
    string(REGEX REPLACE "[{}-]" "" digits "${guid}")
    string(LENGTH "${digits}" length)
    if(NOT length EQUAL 32 OR NOT digits MATCHES "^[0-9a-fA-F]+$")
        message(FATAL_ERROR "Invalid product GUID: ${key}")
    endif()
    string(SUBSTRING "${digits}" 0 8 a)
    string(SUBSTRING "${digits}" 8 4 b)
    string(SUBSTRING "${digits}" 12 4 c)
    set(bytes "")
    foreach(offset RANGE 16 30 2)
        string(SUBSTRING "${digits}" ${offset} 2 byte)
        string(APPEND bytes "0x${byte},")
    endforeach()
    set(${output} "{0x${a},0x${b},0x${c},{${bytes}}}" PARENT_SCOPE)
endfunction()

foreach(key clsid profileGuid displayInputGuid displayMarkedGuid
            switchLanguageGuid fullHalfGuid settingsGuid)
    jev_guid_initializer(${key} JEV_${key})
endforeach()
foreach(key userDirectory settingsFilename pipePrefix)
    string(JSON JEV_${key} GET "${JEV_PRODUCT_JSON}" "${key}")
endforeach()
configure_file("${CMAKE_SOURCE_DIR}/cmake/JevIdentity.h.in"
               "${WINMCBOPOMOFO_GENERATED_DIR}/JevIdentity.h" @ONLY)
